image:
  repository: kanei0415/ktcloud-msa-frontend
  tag: c084688ad7e6e368f78dd14a5f23c73d8bba854c
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

runtimeConfig:
  API_GATEWAY_ENDPOINT: /ktcloud-msa/user-api/api/v1
