image:
  repository: kanei0415/ktcloud-msa-user-api-gateway
  tag: e6699d9a29f65f8207d2f1f9134a75c6338368a6
  pullPolicy: IfNotPresent

addons:
  

service:
  type: ClusterIP

appConfig:
  spring:
    application:
      name: user-api-gateway
  grpc:
    client:
      auth-service:
        address: 'static://auth-service-release.svc.ktcloud-market-msa-release:9090'
        negotiation-type: plaintext
      product-service:
        address: 'static://product-service-release.svc.ktcloud-market-msa-release:9090'
        negotiation-type: plaintext
      order-service:
        address: 'static://order-service-release.svc.ktcloud-market-msa-release:9090'
        negotiation-type: plaintext
      inventory-service:
        address: 'static://inventory-service-release.svc.ktcloud-market-msa-release:9090'
        negotiation-type: plaintext
  jwt:
    secret: 'v7S6A9yB2E5H8KcNfUjXnZr4u7x!A%D*G-'
  server:
    port: 8080
  management:
    endpoints:
      web:
        base-path: /
        path-mapping:
          health: healthz
    endpoint:
      health:
        show-details: always
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      groups-order: DESC
      operations-sorter: alpha
    api-docs:
      path: /v3/api-docs