image:
  repository: kanei0415/ktcloud-msa-order-service
  tag: 3f9b8cda86f41332ea2c48fc6b4495e72245f554
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

externalSecret:
  enabled: true
  targetName: order-service-secrets
  awsSecretName: kt-cloud-cluster/order-service
  keys:
    - secretKey: password
      property: DB_PASSWORD
    - secretKey: postgres-password
      property: DB_PASSWORD

redis:
  enabled: false

postgresql:
  enabled: true
  fullnameOverride: order-postgres
  architecture: standalone
  global:
    security:
      allowInsecureImages: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r0
  auth:
    username: order-service
    database: order_db
    existingSecret: order-service-secrets
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
  primary:
    persistence:
      enabled: true
      storageClass: ebs-sc
      size: 5Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi

appConfig:
  spring:
    application:
      name: order-service
    datasource:
      url: jdbc:postgresql://order-postgres:5432/order_db
      username: order-service
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create
      generate-ddl: true
      show-sql: true
    kafka:
      bootstrap-servers: kafka.kafka.svc.cluster.local:9092
      consumer:
        group-id: order-service-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topic:
        inventory-reserved-result: inventory-reserved-result-topic
        inventory-reserve-request: inventory-reserve-request-topic
  server:
    port: 8080
  grpc:
    server:
      port: 9090
  management:
    endpoints:
      web:
        base-path: /
        path-mapping:
          health: healthz
    endpoint:
      health:
        show-details: always
