image:
  repository: kanei0415/ktcloud-msa-product-service
  tag: 42f30b763909d7c8022b515a93d1f8a16beaf38e
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

appConfig:
  spring:
    application:
      name: product-service
    datasource:
      url: jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/product_db
      username: product-service
      password: product-service
      driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create
      generate-ddl: true
      show-sql: true
  server:
    port: 8080
  grpc:
    server:
      port: 9090
  management:
    endpoints:
      web:
        base-path: /
        path-mapping:
          health: healthz
    endpoint:
      health:
        show-details: always