image:
  repository: kanei0415/ktcloud-msa-product-service
  tag: 42f30b763909d7c8022b515a93d1f8a16beaf38e
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

externalSecret:
  enabled: true
  targetName: product-service-secrets
  awsSecretName: kt-cloud-cluster/product-service
  keys:
    - secretKey: password
      property: DB_PASSWORD
    - secretKey: postgres-password
      property: DB_PASSWORD

redis:
  enabled: false

postgresql:
  enabled: true
  fullnameOverride: product-postgres
  architecture: standalone
  global:
    security:
      allowInsecureImages: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r0
  auth:
    username: product-service
    database: product_db
    existingSecret: product-service-secrets
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
  primary:
    persistence:
      enabled: true
      storageClass: ebs-sc
      size: 5Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi

appConfig:
  spring:
    application:
      name: product-service
    datasource:
      url: jdbc:postgresql://product-postgres:5432/product_db
      username: product-service
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create
      generate-ddl: true
      show-sql: true
  server:
    port: 8080
  grpc:
    server:
      port: 9090
  management:
    endpoints:
      web:
        base-path: /
        path-mapping:
          health: healthz
    endpoint:
      health:
        show-details: always
